<!-- ------------------------------------------------------------------------------ -->
# Naming Clarity
<!-- ------------------------------------------------------------------------------ -->

## Naming for clarity {.smaller}

\

It may seem inconsequential, but carefully naming variables and methods can greatly
improve the readability of code.

\

Since _"code is read more than it is run"_ this is important for future you, but also
for anyone you collaborate with or who might use your code in future.

\

It helps to make code self-documenting, reducing future bugs due to misunderstandings.

\

Here we cover some key considerations when writing code.

<!-- ------------------------------------------------------------------------------ -->

## Naming for clarity {.smaller}

::: {.incremental}
- Show the intention -- how will someone else (future you) read it?
- Use readable, pronounceable, memorable, and searchable names:
  ```
  ms    --> mass
  chclt --> chocolate
  stm   --> stem
  ```
  avoid abbreviations and single letters unless clear
- Employ concept consistency \
  e.g. only one of `get_`, `retrive_`, `fetch_` in the code base
- Describe content rather than storage type \
  Use plurals to indicate groups \
  Name booleans using prefixes like `is_`, `has_`, `can_` and avoid negations like `not_`:
  ```
  array       --> dogs                    float_or_int --> returns_int
  age_int     --> age                     not_plant    --> is_plant
  country_set --> countries               sidekick     --> has_sidekick
  ```
:::

<!-- ------------------------------------------------------------------------------ -->

## Explaining Variables {.smaller}

Without explaining variable: \

```python

def calculate_fare(age):
    if (age < 14):
        return 3
        ...
```

\

With explaining variable: \

```python

def calculate_fare(age):
    is_child = age < 14
    if (is_child):
        return 3
    ...
```

<!-- ------------------------------------------------------------------------------ -->

## Explaining Variables {.smaller}

Without an explaining variable, it is hard to see what this code is doing:

```python
import re

re.search("^\\+?[1-9][0-9]{7,14}$", "Sophie: CV56 9PQ, +12223334444")
```

\

::: {.fragment}
With explaining variables it is easier to see the intention. \
The code is more self-documenting.

```python
import re

phone_number_regex = "^\\+?[1-9][0-9]{7,14}$"
re.search(phone_number_regex, "Sophie: CV56 9PQ, +12223334444")
```
:::

<!-- ------------------------------------------------------------------------------ -->

## Exercise 4 {.smaller}

Look through the code for method or variable names that could be improved or
clarified and update them.^[Note: if you are using an IDE like Intellij or VSCode you can use automatic renaming.]

Does this make the code easier to follow?

\

::: {style="font-size: 80%;"}

Consider the following, can you find an example of each:

:::: {.columns}
::: {.column width="65%"}
- Show the intention -- how will someone else (future you) read it
- Use readable, pronounceable, memorable, and searchable names
- Keep it simple using technical terms where appropriate
- Employ concept consistency in the code base
:::
::: {.column width="35%"}
- Describe content rather than type
- Use plurals to indicate groups
- Name booleans using prefixes 
- Use explaining variables
:::
::::

:::

<!-- ------------------------------------------------------------------------------ -->
